name: build-test-deploy
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
    inputs:
      node-package-manager:
        description: "Package manager"
        default: "pnpm"
        required: true
        type: string
      node-version:
        description: "Node version"
        required: true
        type: string
      language:
        description: "language"
        required: true
        type: string
      deepsource:
        description: "deepsource"
        required: true
        type: string
      python-version:
        description: "Python version"
        required: true
        default: "3.11"
        type: string
      skip-tests:
        description: "Skip tests"
        required: false
        default: true
        type: boolean
      pnpm-version:
        description: "pnpm version"
        required: false
        default: "9.12.2"
        type: string

env:
  DATADOG_API_KEY: ${{secrets.DATADOG_API_KEY}}

jobs:
  initial:
    uses: hsandovaltides/shared_workflows/.github/workflows/teams-notification.yml@main
    secrets: inherit
    with:
      node-version: ${{ inputs.node-version }}
      description: ${{ github.event.repository.name }}

  test:
    runs-on: ubuntu-latest
    
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
        if: inputs.skip-tests == false

      - name: Install Python
        uses: actions/setup-python@v5
        if: inputs.skip-tests == false
        with:
          python-version: ${{ inputs.python-version }}
          
      
      - name: Install node.js
        uses: actions/setup-node@v4
        if: inputs.skip-tests == false
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install modules pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
        if: inputs.node-package-manager == 'pnpm' && inputs.skip-tests == false

      - run: pnpm install
        if: inputs.node-package-manager == 'pnpm' && inputs.skip-tests == false

      - name: Run npm test
        run: pnpm run test
        continue-on-error: true
        if: inputs.node-package-manager == 'pnpm' && inputs.skip-tests == false
      
      - run: npm install
        if: inputs.node-package-manager == 'npm' && inputs.skip-tests == false
      
      - name: Run npm test
        run: pnpm run test
        continue-on-error: true
        if: inputs.node-package-manager == 'npm' && inputs.skip-tests == false

      - name: show coverage
        run: ls ./
        continue-on-error: true
        if: inputs.skip-tests == false

      - name: Report test coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ inputs.deepsource }}
        run: |
          curl https://deepsource.com/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key ${{ inputs.language }} --value-file ./coverage/cobertura-coverage.xml
        continue-on-error: true
        if: inputs.skip-tests == false

        

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEV_REGION }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      
      - name: Install node.js
        uses: actions/setup-node@v4

        
      - name: Install modules npm
        run: npm install
        if: inputs.node-package-manager == 'npm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
        if: inputs.node-package-manager == 'pnpm'
      
      - name: Install modules pnpm
        run: pnpm install
        if: inputs.node-package-manager == 'pnpm'
      
      - name: Set stage based on branch
        id: set-stage
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "stage=pro" >> $GITHUB_OUTPUT
            else
          echo "stage=dev" >> $GITHUB_OUTPUT
          fi

      - name: Print Deploy
        env:
          NODE_OPTIONS: "--no-experimental-require-module"
        run: ./node_modules/serverless/bin/serverless.js print --stage ${{ steps.set-stage.outputs.stage }}
      
      - name: Deploy App To Aws
        run: ./node_modules/serverless/bin/serverless.js deploy --stage ${{ steps.set-stage.outputs.stage }}
      
        

  
